# -*- coding: utf-8 -*-
"""RovnerMotzFinalProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nN8vuhtLDrrlcXeC2_kOuTomrPit2-rT
"""

